[defaults]
preset = memgpt_chat
persona = sam_pov
human = basic

[model]
model = memgpt-openai
model_endpoint = https://inference.memgpt.ai
model_endpoint_type = openai
model_wrapper = airoboros-l2-70b-2.1
context_window = 16384

[embedding]
embedding_endpoint_type = hugging-face
embedding_endpoint = https://embeddings.memgpt.ai
embedding_model = BAAI/bge-large-en-v1.5
embedding_dim = 1024
embedding_chunk_size = 300

[archival_storage]
type = chroma
path = /root/.memgpt/chroma

[recall_storage]
type = sqlite
path = /root/.memgpt

[metadata_storage]
type = sqlite
path = /root/.memgpt

[version]
memgpt_version = 0.3.17

[client]
anon_clientid = 00000000-0000-0000-0000-000000000000